name = "CIGARStrings"
uuid = "e5b51f81-6ffd-4e20-bbec-f118e37ea906"
version = "0.1.4"
authors = ["Jakob Nybo Nissen <jakobnybonissen@gmail.com>"]

[deps]
MemoryViews = "a791c907-b98b-4e44-8f4d-e4c2362c6b2f"

[compat]
FormatSpecimens = "1.3.0"
MemoryViews = "0.2.1, 0.3"
Test = "1.11"
julia = "1.11"

[extras]
FormatSpecimens = "3372ea36-2a1a-11e9-3eb7-996970b6ffbd"
MemoryViews = "a791c907-b98b-4e44-8f4d-e4c2362c6b2f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "MemoryViews", "FormatSpecimens"]
